name: Francuski Buldog
title: contentplate online
copywrite: "  Copyright © 2021 Francuski Buldog"
logo: /assets/uploads/frenchie-180x60-tiny.png
footer_logo: /assets/uploads/cropped-site-icon-tiny-150x150.png
favicon: /assets/uploads/favicon.ico
address: Dhaka, Bangladesh
email: office@francuskibuldog.rs
phone: "+8801856120120"
