name: Dogo Argentino
title: Argentinski Pas
description: Dogo Argentino štenci prodaja
copywrite: "  Copyright © 2021 ne.bez.incidenta"
logo: /assets/uploads/frenchie-180x60-tiny.png
footer_logo: /assets/uploads/cropped-site-icon-tiny-150x150.png
favicon: /assets/uploads/favicon.ico
address: Beograd, Srbija
email: +381 63 / 224 - 166
phone: +381 63 / 224 - 166
