# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: main # Branch to update (master by default)

# when using the default proxy server port
local_backend: true

display_url: "https://laughing-torvalds-999fb8.netlify.app"

media_folder: "assets/uploads" # Folder where user uploaded files should go

#publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    label_singular: Post
    folder: "_posts" # The path to the folder where the documents are stored
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "image", name: "image", widget: "image"} 
  # PAGES
  - name: "pages"
    label: "pages"
    label_singular: Page
    folder: "_pages"
    sort: "title:asc"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {
          label: "Title",
          name: "title",
          widget: "string",
          required: true,
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - {label: "Body", name: "body", widget: "markdown"}
      
  #Others
  - name: others
    label: Others
    editor:
      preview: false
    files:
      - file: _data/navigation.yml
        label: Main Menus
        name: main-menus
        fields:
          - label: Main menus
            name: main-menus
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: "Path (example: /path/)", name: url, widget: string }
                
      - file: _data/settings.yml
        label: Settings
        name: settings
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Meta Description",
              name: "description",
              widget: "string",
              required: false,
            }
          - { label: "Copywrite", name: "copywrite", widget: "string" }
          - { label: Logo, name: logo, widget: image, choose_url: false}
          - { label: Footer Logo, name: footer_logo, widget: image, choose_url: false}
          - { label: Favicon, name: favicon, widget: image, choose_url: false}
          - { label: "Address", name: address, widget: "text" }
          - { label: "Email", name: email, widget: "string" }
          - { label: "Phone", name: phone, widget: "string" }
      
      - file: _data/socials.yml
        label: Social Profile
        name: socials
        fields:
          - { label: Facebook, name: facebook, widget: string, required: false }
          - { label: instagram, name: instagram, widget: string, required: false }
      - file: _data/contents/footer.yml
        label: Footer
        name: footer
        fields:
          - { label: "Title", name: title, widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "text",
              required: true,
            }
          - { label: "Our Office Label", name: our-office-label, widget: "string", default: 'Our Offices' }
          - { label: "Working Hours", name: working-hours-label, widget: "string", default: "Working Hours" }
          - { label: "Contact Us", name: contact-us-label, widget: "string", default: "Contact" }
#static page
  - name: home_page
    label: Home Page
    editor:
      preview: false
    files:
      - file: _data/home/hero.yml
        label: Hero Section
        name: hero
        fields:
          - {label: image, name: image, widget: image, choose_url: false }
          - {label: tagline, name: tagline, widget: string }
          - {label: title, name: title, widget: string }
          - {label: subtitle, name: subtitle, widget: string }
#nastala
      - file: _data/home/nastala.yml
        label: nastala Section
        name: nastala
        fields:
          - {label: image, name: image, widget: image, choose_url: false }
          - {label: tagline, name: tagline, widget: string }
          - {label: title, name: title, widget: string }
          - {label: description, name: description, widget: text }
#feature
      - file: _data/home/feature.yml
        label: feature Section
        name: feature_section
        fields:
          - label: Group Data
            name: group
            widget: list
            fields:
              - { label: Image, name: image, widget: image, choose_url: false }
              - { label: Title, name: title, widget: string }
              - { label: "Description", name: description, widget: text }
#najbolji
      - file: _data/home/najbolji.yml
        label: najbolji Section
        name: najbolji
        fields:
          - {label: image, name: image, widget: image, choose_url: false }
          - {label: title, name: title, widget: string }
          - {label: description, name: description, widget: text }
          - label: feature Data
            name: feature
            widget: list
            fields:
              - { label: Name, name: name, widget: string}
              - { label: Image, name: image, widget: image, choose_url: false }
              - { label: "Description", name: description, widget: text }
              - { label: Link, name: link, widget: string }
#zapratite
      - file: _data/home/zapratite.yml
        label: zapratite Section
        name: zapratite
        fields:
          - {label: title, name: title, widget: string }
#utisci
      - file: _data/home/utisci.yml
        label: utisci Section
        name: utisci
        fields:
          - {label: tagline, name: tagline, widget: string }
          - {label: title, name: title, widget: string }
          - {label: description, name: description, widget: text }
          - label: Clients
            name: clients
            widget: list
            fields:
              - { label: Image, name: image, widget: image, choose_url: false }
              - { label: "Description", name: description, widget: text }
              - { label: address, name: address, widget: string }
#obraduj
      - file: _data/home/obraduj.yml
        label: obraduj Section
        name: obraduj
        fields:
          - {label: title, name: title, widget: string }
          - {label: description, name: description, widget: text }
          - { label: Image, name: image, widget: image, choose_url: false }
            